### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [ri57-sibsutis/password-generator#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:
1. В [wiki](https://github.com/ri57-sibsutis/password-generator/wiki) проекта написана статья с ТЗ.
2. В [issues](https://github.com/ri57-sibsutis/password-generator/issues) созданы задачи.
3. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by Sofya-Kl** [comment]
Составили ТЗ

**Comment by evgeny-p** [comment]
Вопросы, которые следует раскрыть в ТЗ:
1. Приложение будет консольным или оконным? На чем планируется реализовывать интерфейс?
2. > Продукт, помогающий пользователю создать запоминающийся, читаемый и устойчивый к взлому пароль.
   
   Свойствами легкости для запоминания и читаемости будут обладать все пароли? Возможно, это стоит сделать дополнительной отключаемой опцией.
3. > Doug McIlroy, the inventor of Unix pipes and one of the founders of the Unix tradition, had this to say at the time:
   > 1. (…)
   > 2. Expect the output of every program to become the input to another, as yet unknown, program. Don't clutter output with extraneous information. Avoid stringently columnar or binary input formats. **Don't insist on interactive input.**
   
   [Eric Steven Raymond, The Art of Unix Programming: Basics of the Unix Philosophy](http://www.catb.org/esr/writings/taoup/html/ch01s06.html)
   Подумайте над тем, чтобы в дополнение реализовать неинтерактивный режим работы.

Нужен хотя бы примерный план работ. Можно не сразу заводить задачи, а оставить примерную декомпозицию в комментарии.

**Comment by Sofya-Kl** [comment]
Составили ТЗ [2]

**Comment by evgeny-p** [comment]
Обсудили на паре.

Нужно детальнее проработать интерфейс и определиться, как пользователь будет выбирать допустимые наборы символов.

Не откладывайте с заведением задач. Возможно, в процессе их формулирования возникнет необходимость доработки ТЗ.

**Comment by evgeny-p** [comment]
Для начала работы ТЗ и задач в текущем состоянии достаточно. Предлагаю начинать работу, а возникающие замечания и вопросы решать по мере поступления.
