### ISSUE TITLE
7. Сборка готовых подпрограмм в главную функцию.

### ISSUE THREAD

**Issue by Sofya-Kl** [ri57-sibsutis/password-generator#8]
Написание исходного файла main.c. Написание файла  strings.h, содержащего прототипы функций. Подключение файла strings.h с помощью директивы #include "strings.h"
в исходном файле, использующем эти функции.

**Comment by evgeny-p** [comment]
Эта задача под вопросом.
Функцию main можно начать писать параллельно с написанием пользовательского ввода.

Не вижу смысла выделять в задачу наполнение заголовочного файла. По идее, все функции должны быть покрыты юнит-тестами. Для того, чтобы функцию можно было вызвать из тестов, нужно ее объявление. Объявление размещается в заголовочном файле. Следовательно, написание каждой публичной функции означает редактирование файлов `.c` и `.h`. Таким образом, для этой задачи не остается работы.
